grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 1
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: true
    search_param_grid:
      fit_intercept:
      - true
      - false
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
    search_param_grid:
      min_samples_leaf:
      - 2
      - 3
      max_depth:
      - 3
      - 4
      - 5
      min_samples_split:
      - 2
      - 3
  module_2:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      loss: squared_error
      learning_rate: 0.1
      criterion: friedman_mse
    search_param_grid:
      min_samples_leaf:
      - 2
      - 3
      max_depth:
      - 3
      - 4
      - 5
      min_samples_split:
      - 2
      - 3     
